services:
  oxidized:
    image: oxidized/oxidized:latest
    container_name: oxidized
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./config:/home/oxidized/.config/oxidized/config:ro
      - ./git-repos:/var/lib/oxidized/git-repos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
